maint(deps): bump org.springframework.boot from 3.0.6 to 3.1.2 in /java/message-service (#729)
Bumps
[org.springframework.boot](https://github.com/spring-projects/spring-boot)
from 3.0.6 to 3.1.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot's
releases</a>.</em></p>
<blockquote>
<h2>v3.1.2</h2>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Native reflection hints missing for nested properties declared in a
superclass <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36448">#36448</a></li>
<li>Connecting to Mongo fails with an UnknownHostException when
spring.data.mongodb.additional-hosts is configured <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36441">#36441</a></li>
<li>Auto-configured ExemplarSampler bean only backs off when a
DefaultExemplarSampler is defined <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36429">#36429</a></li>
<li>OTel Span is missing required attributes <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36423">#36423</a></li>
<li>Auto-configured JacksonJsonpMapper is conditional on an ObjectMapper
bean but does not use such a bean <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36409">#36409</a></li>
<li>Application fails to start when <code>@Import</code>ing a
<code>@ConfigurationProperties</code> class that is eligible for
constructor binding <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36359">#36359</a></li>
<li>Only one health group can be exposed using
management.endpoint.health.group.xxx.additional-path=server:/newpath
when using Jersey <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36276">#36276</a></li>
<li>Mongo auto-configuration fails when username or password properties
contains a colon (<code>:</code>) or at-sign (<code>@</code>) <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36261">#36261</a></li>
<li>MockitoPostProcessor doesn't check FactoryBean.OBJECT_TYPE_ATTRIBUTE
correctly <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36230">#36230</a></li>
<li>ImportsContextCustomizer does not support AliasFor <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36209">#36209</a></li>
<li>Saml2RelyingPartyRegistrationConfiguration can choose the wrong
RelyingPartyRegistration.Builder when using a metadata file with
multiple providers <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36163">#36163</a></li>
<li>ConfigurationPropertiesReportEndpoint does not display primitive
wrapper types <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36160">#36160</a></li>
<li>ConfigurationPropertyName#equals is not symmetric when element has
trailing dashes <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36145">#36145</a></li>
<li>ScheduledTasksEndpoint throws NPE if PeriodicTrigger is used with
custom SchedulingConfigurer <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36129">#36129</a></li>
<li>Java system properties can not be applied to RestTemplate HttpClient
connection in some cases <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36123">#36123</a></li>
<li>Excluding auto-configuration class that relates to a
TemplateAvailabilityProvider causes property binding to fail for native
images <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36121">#36121</a></li>
<li>When using Flyway 9.20.0, auto-configuration fails with a
NoSuchMethodError due to the removal of Oracle-related methods from
FluentConfiguration <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36099">#36099</a></li>
<li>Dependency management for Selenium 4.8.x is incorrect <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/36077">#36077</a></li>
<li>Slice test annotations do not include SslAutoConfiguration <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/36038">#36038</a></li>
<li>Methods in KafkaConnectionDetails are named inconsistently <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/35733">#35733</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Documented Servlet container system requirements are out of date <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36355">#36355</a></li>
<li>Update the javadoc of ClientHttpRequestFactories to describe the
ClientHttpRequestFactory implementations that it supports <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36268">#36268</a></li>
<li>Polish formatting in &quot;Running Spring Batch Jobs on
Startup&quot; <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36233">#36233</a></li>
<li>Improve Kubernetes liveness and readiness probes customization
documentation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36219">#36219</a></li>
<li>Document auto-configuration of underlying HTTP client when using
WebClient or RestTemplate <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36215">#36215</a></li>
<li>Polish Kafka Properties Docs <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36142">#36142</a></li>
<li>Fix typo in the Using R2DBC section of the reference documentation
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36139">#36139</a></li>
<li>Document observability auto-configuration for HTTP clients <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36131">#36131</a></li>
<li>Improve documentation for baggage propagation into MDC <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36112">#36112</a></li>
<li>Javadoc of RestTemplateBuilder.requestFactory(Function) links to
deprecated ClientHttpRequestFactorySupplier <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36097">#36097</a></li>
<li>Javadoc of ConstructorBound and ConfigurationProperties links to
deprecated ConstructorBinding annotation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36095">#36095</a></li>
<li>Add Javadoc since to ImageReference.inTaglessForm() <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36054">#36054</a></li>
<li>Fix typo in docker compose service connections note <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/36016">#36016</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to ActiveMQ 5.18.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36332">#36332</a></li>
<li>Upgrade to Dependency Management Plugin 1.1.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36435">#36435</a></li>
<li>Upgrade to Groovy 4.0.13 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36333">#36333</a></li>
<li>Upgrade to Hibernate 6.2.6.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36334">#36334</a></li>
<li>Upgrade to Hibernate Validator 8.0.1.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36335">#36335</a></li>
<li>Upgrade to Infinispan 14.0.12.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36336">#36336</a></li>
<li>Upgrade to Jakarta WebSocket 2.1.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36337">#36337</a></li>
<li>Upgrade to Janino 3.1.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/36338">#36338</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/b9177e5786e9908aae3948f5c6ca76dccfe292ee"><code>b9177e5</code></a>
Release v3.1.2</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/fe67932a56a4157387b60a93ebf2226044d38576"><code>fe67932</code></a>
Merge branch '3.0.x' into 3.1.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/960f0ea1da99c145ce30580ffc2133066295a3eb"><code>960f0ea</code></a>
Revert &quot;Upgrade to R2DBC Pool 1.0.1.RELEASE&quot;</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/46a83d7defef539a1d5c408ad7ae4570d4d85c12"><code>46a83d7</code></a>
Upgrade to Spring HATEOAS 2.1.2</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/8ee8bb440f9abc1b03ade9f02a1d62b48c4c7555"><code>8ee8bb4</code></a>
Upgrade to R2DBC Postgresql 1.0.2.RELEASE</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/da5cb6d3abc71b909e2c91bd7f54a906faff23ff"><code>da5cb6d</code></a>
Upgrade to R2DBC Pool 1.0.1.RELEASE</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/e20063831175dcba6cef5454540142175604b98b"><code>e200638</code></a>
Upgrade to R2DBC MSSQL 1.0.2.RELEASE</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/651a1456d1856c57c4d1a05dc4bb7a1e858b50a0"><code>651a145</code></a>
Merge branch '3.0.x' into 3.1.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/e30b3fe4f297ef19ca0ea85e2b2946db6852dc86"><code>e30b3fe</code></a>
Upgrade to Spring HATEOAS 2.0.6</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/277efdc6b13ed7e73eb7fe9ef9b07496be40ef58"><code>277efdc</code></a>
Upgrade to R2DBC Postgresql 1.0.2.RELEASE</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.0.6...v3.1.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot&package-manager=gradle&previous-version=3.0.6&new-version=3.1.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>